#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common-functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
if [[ -f "$PLUGIN_AVAILABLE_PATH/docker-options/functions" ]]; then
  source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"
fi

# non-generic functions

service_create() {
  local SERVICE="$1"
  local DOMAIN="$2"
  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a name for the service"
  [[ -z "$DOMAIN" ]] && dokku_log_fail "Please specify domain name for the service like mail.example.com"
  [[ ! -d "$PLUGIN_DATA_ROOT/$SERVICE" ]] || dokku_log_fail "$PLUGIN_SERVICE service $SERVICE already exists"
  SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"; LINKS_FILE="$SERVICE_ROOT/LINKS"

  if ! docker images | grep -e "^$PLUGIN_IMAGE " | grep -q " $PLUGIN_IMAGE_VERSION " ; then
    docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" || dokku_log_fail "$PLUGIN_SERVICE image $PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION pull failed"
  fi

  mkdir -p "$SERVICE_ROOT" || dokku_log_fail "Unable to create service directory"
  mkdir -p "$SERVICE_ROOT/data" || dokku_log_fail "Unable to create service data directory"
  mkdir -p "$SERVICE_ROOT/config" || dokku_log_fail "Unable to create service config directory"
  
  echo $DOMAIN>"$SERVICE_ROOT/domain"
  touch "$SERVICE_ROOT/config/postfix-accounts.cf"
  PASSWORD=$(openssl rand -hex 12)
  docker run --rm -e "MAIL_USER=mail@$DOMAIN" -e "MAIL_PASS=$PASSWORD" "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" /bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s SHA512-CRYPT -u $MAIL_USER -p $MAIL_PASS)"' >> "$SERVICE_ROOT/config/postfix-accounts.cf"
  docker run --rm -v "$SERVICE_ROOT/config:/tmp/docker-mailserver" -ti "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" generate-dkim-config
  touch "$LINKS_FILE"

  if [[ -n $MAILSERVER_CUSTOM_ENV ]]; then
    echo "$MAILSERVER_CUSTOM_ENV" | tr ';' "\n" > "$SERVICE_ROOT/ENV"
  else
    echo "" > "$SERVICE_ROOT/ENV"
  fi
  service_create_container "$SERVICE" "$DOMAIN"
}

service_create_container() {
  local SERVICE="$1"
  local DOMAIN="$2"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"

  ID=$(docker run -h "$DOMAIN" --name "$SERVICE_NAME" -v "$SERVICE_ROOT/data/mail:/var/mail" -v "$SERVICE_ROOT/data/state:/var/mail-state" -v "$SERVICE_ROOT/config:/tmp/docker-mailserver/" --env-file="$SERVICE_ROOT/ENV" -d --restart always --label dokku=service --label dokku.service=mailserver "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION")
  echo "$ID" > "$SERVICE_ROOT/ID"

  dokku_log_verbose_quiet "Waiting for container to be ready"
  docker run --rm --link "$SERVICE_NAME:$PLUGIN_COMMAND_PREFIX" dokkupaas/wait:0.2 -p "$PLUGIN_DATASTORE_WAIT_PORT" > /dev/null

  dokku_log_info2 "$PLUGIN_SERVICE container created: $SERVICE"
  service_info "$SERVICE"
}

service_start() {
  local SERVICE="$1"
  local QUIET="$2"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local ID=$(docker ps -f status=running | grep -e "$SERVICE_NAME$" | awk '{print $1}') || true
  if [[ -n $ID ]]; then
    [[ -z $QUIET ]] && dokku_log_warn "Service is already started"
    return 0
  fi

  dokku_log_info1_quiet "Starting container"
  local PREVIOUS_ID=$(docker ps -f status=exited | grep -e "$SERVICE_NAME$" | awk '{print $1}') || true
  local IMAGE_EXISTS=$(docker images | grep -e "^$PLUGIN_IMAGE " | grep -q " $PLUGIN_IMAGE_VERSION " && true)

  if [[ -n $PREVIOUS_ID ]]; then
    docker start "$PREVIOUS_ID" > /dev/null
    service_port_unpause "$SERVICE"
    dokku_log_info2 "Container started"
  elif $IMAGE_EXISTS; then
    service_create_container "$SERVICE"
  else
    dokku_log_verbose_quiet "Neither container nor valid configuration exists for $SERVICE"
  fi
}

service_password() {
    local SERVICE="$1"
    local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
    local PASSWORD="$(cat "$SERVICE_ROOT/PASSWORD")"
    echo "$PASSWORD"
}

service_url() {
  local SERVICE="$1"
  local PASSWORD="$(service_password "$SERVICE")"
  local SERVICE_ALIAS="$(service_alias "$SERVICE")"
  echo "$PLUGIN_SCHEME://$SERVICE:$PASSWORD@$SERVICE_ALIAS:${PLUGIN_DATASTORE_PORTS[0]}"
}
